[package]
name = "v090b2-add"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-console = "0.3.0"
sycamore = "0.9.0-beta.2"
wasm-bindgen = "0.2.92"
web-sys = { version="0.3.69", features=["EventTarget", "PointerEvent"] }